[package]
name = "nng-c-sys"
version = "1.12.4"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"
keywords = ["nng", "nanomsg"]
categories = ["api-bindings"]
description = "Bindings nng C library"
license = "BSL-1.0"
repository = "https://github.com/DoumanAsh/nng-c-sys"
documentation = "https://docs.rs/crate/nng-c-sys"

[build-dependencies.pkg-config]
version = "0.3"
optional = true

[build-dependencies.bindgen]
version = "0.73"
optional = true

[build-dependencies.cmake]
version = "0.1"

[features]
# Used internally to generate lib.rs
build-bindgen = ["bindgen"]
# Enables HTTP transport code
http = []
# Enables Websocket transport code (this automatically enables http transport)
websocket = ["http"]
# Enables TLS
tls = []
# Enables TLS but rely on automatic CMake discovery
tls-no-vendored = ["tls"]
# Enables TLS but rely on pkg-config to discover it
tls-pkg-config = ["tls-no-vendored", "pkg-config"]
# Enables statistics
stats = []
