name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    if: github.event.pull_request.draft == false
    uses: DoumanAsh/douman-ci/.github/workflows/rust.yml@master
    with:
      runs-on: ${{ matrix.os }}
      cargo-no-features: true
      cargo-features: "http,websocket,stats"
